### ISSUE TITLE
Database Tables Disappears and System Crashes with Docker-Compose Configuration

### ISSUE THREAD

**Issue by stupidboy12138** [n4ze3m/dialoqbase#56] opened 2023-07-17 10:50 UTC
Error: P3009

migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
The `init` migration started at 2023-07-17 10:39:24.473380 UTC failed
![e7ca216e-13c0-4b58-9188-1e5048273a4d](https://github.com/n4ze3m/dialoqbase/assets/32326223/2277d4e8-6d5a-4890-b298-791117519714)

**Comment by n4ze3m** [comment] 2023-07-17 13:58
Did you try to update from version 0.0.18 to 0.0.19 or an earlier version like 0.0.2 or 0.0.3? There are a few breaking changes from versions 0.0.1 to 0.0.5; I apologize for that. If you attempted to update from an early version, please re-clone this repo

**Comment by stupidboy12138** [comment] 2023-07-18 03:01
No, I did not update. After 0.0.19 ran successfully, after a period of time I suddenly found that the service was suspended and an appeal error was reported, and often I uploaded the document after deleting the document. The whole service also crashed. Can you help me to test it? Do you frequently delete documents before uploading them? This has happened to me many times, and every time I have to delete all the data and rebuild a service

**Comment by stupidboy12138** [comment] 2023-07-18 03:01
> Did you try to update from version 0.0.18 to 0.0.19 or an earlier version like 0.0.2 or 0.0.3? There are a few breaking changes from versions 0.0.1 to 0.0.5; I apologize for that. If you attempted to update from an early version, please re-clone this repo

No, I did not update. After 0.0.19 ran successfully, after a period of time I suddenly found that the service was suspended and an appeal error was reported, and often I uploaded the document after deleting the document. The whole service also crashed. Can you help me to test it? Do you frequently delete documents before uploading them? This has happened to me many times, and every time I have to delete all the data and rebuild a service

**Comment by n4ze3m** [comment] 2023-07-18 18:49
Hey, I will post an update here once I figure out what went wrong.

**Comment by n4ze3m** [comment] 2023-07-22 07:22
Hey, I just released a new version which updated Prisma's version to the latest one. I hope it resolves the migration issues

**Comment by stupidboy12138** [comment] 2023-07-23 08:03
> Hey, I just released a new version which updated Prisma's version to the latest one. I hope it resolves the migration issues

![f3770290-a6ea-44c4-9509-d9cf8f2ea9fc](https://github.com/n4ze3m/dialoqbase/assets/32326223/039412c6-dc51-42f2-a030-b3181b94be2e)
![31bf939e-a590-435b-b4c2-eff1775a72e6](https://github.com/n4ze3m/dialoqbase/assets/32326223/89216b57-ef8f-4ad0-a3c9-185cd7f4867c)
I found another problem. I ran for two or three days after deploying 0.0.19. Three days later, I suddenly found that the system hung up again, and the database tables disappeared. I did not perform any operations during this period, and I did not even move the server. Please help me to check this problem, I also encountered this problem in 0.0.18, it is not the first time, the database table disappears inexplicably and the system cannot be used.

**Comment by stupidboy12138** [comment] 2023-07-23 08:04
I have encountered system crashes many times. One is that the system crashes after deleting the file after uploading the file and then uploading the file again. The other is that the system crashes when nothing is done, and the system database table disappears out of thin air.

**Comment by n4ze3m** [comment] 2023-07-23 08:07
OMG, sorry for that. Are you running the database using Docker?

**Comment by stupidboy12138** [comment] 2023-07-23 08:09
> OMG, sorry for that. Are you running the database using Docker?

yes，i run it with docker
![image](https://github.com/n4ze3m/dialoqbase/assets/32326223/256205d5-e961-45c7-a19f-ea3997b0b1f8)

**Comment by n4ze3m** [comment] 2023-07-23 08:10
Can you try the Supabase database URL instead of Docker?

**Comment by stupidboy12138** [comment] 2023-07-23 08:13
> Can you try the Supabase database URL instead of Docker?

![image](https://github.com/n4ze3m/dialoqbase/assets/32326223/ae7d1c9e-5574-4761-b4c8-7160f14ba45f)
I turned on port mapping

**Comment by n4ze3m** [comment] 2023-07-23 08:19
is it working ?

**Comment by n4ze3m** [comment] 2023-07-23 08:21
I'm totally sorry for what happened. I need to deeply check what happened with Docker.

Can you try this method one last time?

Stop all dialogqase containers:

`docker-compose down` or `docker compose down`

Delete the .postgres directory:

`rmdir .postgres`

Restart the server:

`docker-compose up` or `docker compose up`

**Comment by stupidboy12138** [comment] 2023-07-23 08:21
> is it working ?



> is it working ?

The most recent time, the system ran for about 3 days and then the database table disappeared and the system crashed

**Comment by stupidboy12138** [comment] 2023-07-23 08:22
> .postgres

Yes, after deleting .postgres and rebuilding the container, it can run for a while

**Comment by n4ze3m** [comment] 2023-07-23 08:25
Hmm, so the issue is in the docker-compose configuration. I will try and test with the https://hub.docker.com/r/supabase/postgres image

**Comment by stupidboy12138** [comment] 2023-07-23 08:26
> Hmm, so the issue is in the docker-compose configuration. I will try and test with the https://hub.docker.com/r/supabase/postgres image

I am going to update to version 0.0.20 to see if uploading the document, deleting the document and then uploading the document can be used stably. If there is any problem, I need your help

**Comment by stupidboy12138** [comment] 2023-07-23 13:23
> Hmm, so the issue is in the docker-compose configuration. I will try and test with the https://hub.docker.com/r/supabase/postgres image

![image](https://github.com/n4ze3m/dialoqbase/assets/32326223/97ca0111-9b89-4597-b481-45a6007262b6)
In version 0.0.19, every time you delete a document and then upload it, an error will be reported and the system will crash

**Comment by stupidboy12138** [comment] 2023-07-23 13:24
> Hmm, so the issue is in the docker-compose configuration. I will try and test with the https://hub.docker.com/r/supabase/postgres image

![image](https://github.com/n4ze3m/dialoqbase/assets/32326223/d4168cc9-a56f-4b70-8215-1f846c6c8bb6)
In version 0.0.19, every time you delete a document and then upload it, an error will be reported and the system will crash

**Comment by stupidboy12138** [comment] 2023-07-23 13:33
I have pulled a new image again, uploading and deleting documents repeatedly will not cause an error and cause the system to crash, but I am not sure whether the system database table will be automatically deleted in a few days and cause the system to crash. I hope you can continue to help troubleshoot the problem of the database table being automatically deleted

**Comment by n4ze3m** [comment] 2023-07-23 15:15
I won't close this issue. Let's see how it works in a couple of days. Sorry for all the issues :)

**Comment by n4ze3m** [comment] 2023-07-23 15:18
> In version 0.0.19, every time you delete a document and then upload it, an error will be reported and the system will crash

Btw, that `READONLY You can't write against a read-only replica` is caused by Redis. Hmm, I will check that too

**Closed** 2023-08-05 18:53 UTC
Labels: bug
