### ISSUE TITLE
Authorization token is invalid: The token signature is invalid.

### ISSUE THREAD

**Issue by fittben** [n4ze3m/dialoqbase#36] opened 2023-06-21 23:27 UTC
I keep getting : Authorization token is invalid: The token signature is invalid.

I am trying to connect to a repo, I have tried adding the key classic and the new version several times. Please advise! 

Thanks

**Comment by n4ze3m** [comment] 2023-06-22 07:52
Hi there, I attempted to reproduce the issue locally, but it seems to be working fine for me. Have you granted the token access to the repository? It's possible that the token is lacking the necessary permissions. I'll continue investigating and let you know if I come across a solution. Apologies for any inconvenience caused."

**Comment by n4ze3m** [comment] 2023-06-29 12:46
Closing this issue . Feel free to reopen if the problem still exists. Thank you.

**Closed by n4ze3m** 2023-06-29 12:46 UTC
Labels: bug
