### ISSUE TITLE
Telegram doesnt work

### ISSUE THREAD

**Issue by oalmajalists** [n4ze3m/dialoqbase#87] opened 2023-09-26 12:55 UTC
I got the telegram_bot_token and added it to the control panel and enabled it , but it doesn't work and i don't know what's the error to troubleshoot it , there is no error log .
can you please help ?

**Comment by n4ze3m** [comment] 2023-09-26 14:29
Hey, Did you provide the token from @botfather? And which model did you use ?

**Comment by oalmajalists** [comment] 2023-09-28 06:43
Yes , i provided the token . and i've been using multiple models (GPT-4 and Calude 2 ).
is there any logs i can check ?

**Comment by n4ze3m** [comment] 2023-09-28 07:05
If you are using Docker, you can use `docker-compose logs`,  If you are using Railways, you can view it on their dashboard

**Comment by oalmajalists** [comment] 2023-09-28 07:27
Logs below :
Traceback (most recent call last):
  File "/home/tstsrv/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/home/tstsrv/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tstsrv/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/tstsrv/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/home/tstsrv/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/tstsrv/.local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/tstsrv/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/home/tstsrv/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/tstsrv/.local/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/tstsrv/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tstsrv/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/tstsrv/.local/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))

**Comment by n4ze3m** [comment] 2023-09-28 07:45
idk logs is not from dialoqbase, but it's showing a Python error. 

Can you try once more? You can follow this docs for it: https://dialoqbase.n4ze3m.com/guide/self-hosting.html

**Comment by oalmajalists** [comment] 2023-09-28 08:13
dialoqbase       | bot id XXXXXXXXXXXXXXXXXXXXXXXXX
dialoqbase       | {
dialoqbase       |   id: 2,
dialoqbase       |   provider: 'telegram',
dialoqbase       |   bot_id: 'clmzyrg1q0015ou2kxdmr9rpe',
dialoqbase       |   identifier: 'dialoqbase-telegram-clmzyrg1q0015ou2kxdmr9rpe',
dialoqbase       |   telegram_bot_token: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
dialoqbase       |   is_pause: false,
dialoqbase       |   discord_bot_token: null,
dialoqbase       |   discord_slash_command: 'hey',
dialoqbase       |   discord_slash_command_description: 'Use this command to get help',
dialoqbase       |   discord_application_id: null,
dialoqbase       |   whatsapp_access_token: null,
dialoqbase       |   whatsapp_verify_token: null,
dialoqbase       |   whatsapp_phone_number: null,
dialoqbase       |   slack_auth_token: null,
dialoqbase       |   slack_signing_secret: null,
dialoqbase       |   slack_app_token: null
dialoqbase       | }
dialoqbase       | null
dialoqbase       | null

**Comment by n4ze3m** [comment] 2023-09-28 08:17
Is it work ?

**Comment by oalmajalists** [comment] 2023-09-28 08:24
its not working , when i contact the bot over Telegram it says "Opps! Something went wrong"

**Comment by n4ze3m** [comment] 2023-09-28 08:34
It means an internal server error happened, which may have been caused by the OpenAI API 🤔

**Comment by n4ze3m** [comment] 2023-09-28 08:35
Can you test it on the Playground UI?

**Comment by oalmajalists** [comment] 2023-09-28 08:56
The bot works great using the Playground , and even using the url .
but Telegram bot isnt working .

**Comment by n4ze3m** [comment] 2023-09-28 09:40
Interesting. I will look into it and give an update here

**Comment by n4ze3m** [comment] 2023-09-28 14:00
Hey, I've released the latest version with improved error logging for integration channels. Could you please check it once more to see what happened? Thanks!

**Comment by phpia** [comment] 2023-10-02 10:31
Hi! Im getting this error from telegram bot, using last version 1.0.0:

[App] PrismaClientUnknownRequestError:                                                               
[App] Invalid `prisma.botTelegramHistory.findMany()` invocation in                                   
[App] /home/dialoqbase/server/dist/integration/handlers/telegram.handler.js:22:62              
[App]                                                                                                
[App]   19 if (!bot) {
[App]   20     return "Opps! Bot not found";                                                         
[App]   21 }                                                                                         
[App] → 22 const chat_history = await prisma.botTelegramHistory.findMany(                            
[App] Error occurred during query execution:                                                         
[App] ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: ToSql(0), cause: Some(Error { kind: ConversionError("Unable to fit integer value '6152894103' into an INT4 (32
-bit signed integer)."), original_code: None, original_message: None }) }), transient: false })      
[App]     at zr.handleRequestError (/home/dialoqbase/server/node_modules/@prisma/client/runtime/library.js:122:8480)

Thanks

**Comment by n4ze3m** [comment] 2023-10-02 10:45
Hey, I found out what the issue is with the Telegram bot. It's because the application tried to save a 64-bit integer value into a 32-bit integer field. I will release a patch tonight. :)

**Comment by n4ze3m** [comment] 2023-10-02 14:52
Hey,  patch has been released. Sorry for the issue. Please let me know if the issue still exists. Thanks.

**Comment by phpia** [comment] 2023-10-02 18:25
Tested and working ! :)

**Comment by n4ze3m** [comment] 2023-10-04 17:44
Hey, since this issue has been resolved, I'm closing it. If you encounter the same issue, please reopen it

**Closed by n4ze3m** 2023-10-04 17:44 UTC
Labels: bug
