### ISSUE TITLE
[bug]can not add datasource

### ISSUE THREAD

**Issue by zhangmazi** [n4ze3m/dialoqbase#75] opened 2023-09-09 07:24 UTC
`dialoqbase           | An operation failed because it depends on one or more records that were required but not found. Record to update not found.
dialoqbase           |     at vn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6730)
dialoqbase           |     at vn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6119)
dialoqbase           |     at vn.request (/app/node_modules/@prisma/client/runtime/library.js:123:5839)
dialoqbase           |     at async l (/app/node_modules/@prisma/client/runtime/library.js:128:9763)
dialoqbase           |     at async Queue.queueHandler (/app/queue/index.js:23:17) {
dialoqbase           |   code: 'P2025',
dialoqbase           |   clientVersion: '5.2.0',
dialoqbase           |   meta: { cause: 'Record to update not found.' }
dialoqbase           | }
dialoqbase           | PrismaClientKnownRequestError:
dialoqbase           | Invalid `prisma.botSource.update()` invocation:
dialoqbase           | 
dialoqbase           | 
dialoqbase           | 
dialoqbase           | 
dialoqbase           | An operation failed because it depends on one or more records that were required but not found. Record to update not found.
dialoqbase           |     at vn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6730)
dialoqbase           |     at vn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6119)
dialoqbase           |     at vn.request (/app/node_modules/@prisma/client/runtime/library.js:123:5839)
dialoqbase           |     at async l (/app/node_modules/@prisma/client/runtime/library.js:128:9763)
dialoqbase           |     at async Queue.queueHandler (/app/queue/index.js:77:17) {
dialoqbase           |   code: 'P2025',
dialoqbase           |   clientVersion: '5.2.0',
dialoqbase           |   meta: { cause: 'Record to update not found.' }
dialoqbase           | }
dialoqbase           | Processing queue
dialoqbase           | PrismaClientKnownRequestError:
dialoqbase           | Invalid `prisma.botSource.update()` invocation:
dialoqbase           | 
dialoqbase           | 
dialoqbase           | 
dialoqbase           | 
dialoqbase           | An operation failed because it depends on one or more records that were required but not found. Record to update not found.
dialoqbase           |     at vn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6730)
dialoqbase           |     at vn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6119)
dialoqbase           |     at vn.request (/app/node_modules/@prisma/client/runtime/library.js:123:5839)
dialoqbase           |     at async l (/app/node_modules/@prisma/client/runtime/library.js:128:9763)
dialoqbase           |     at async Queue.queueHandler (/app/queue/index.js:23:17) {
dialoqbase           |   code: 'P2025',
dialoqbase           |   clientVersion: '5.2.0',
dialoqbase           |   meta: { cause: 'Record to update not found.' }
dialoqbase           | }
dialoqbase           | PrismaClientKnownRequestError:
dialoqbase           | Invalid `prisma.botSource.update()` invocation:
dialoqbase           | 
dialoqbase           | 
dialoqbase           | 
dialoqbase           | 
dialoqbase           | An operation failed because it depends on one or more records that were required but not found. Record to update not found.
dialoqbase           |     at vn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6730)
dialoqbase           |     at vn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6119)
dialoqbase           |     at vn.request (/app/node_modules/@prisma/client/runtime/library.js:123:5839)
dialoqbase           |     at async l (/app/node_modules/@prisma/client/runtime/library.js:128:9763)
dialoqbase           |     at async Queue.queueHandler (/app/queue/index.js:77:17) {
dialoqbase           |   code: 'P2025',
dialoqbase           |   clientVersion: '5.2.0',
dialoqbase           |   meta: { cause: 'Record to update not found.' }
dialoqbase           | }
dialoqbase           | Processing queue`

it is faild when i have add datasource.

**Comment by n4ze3m** [comment] 2023-09-09 07:29
Prisma is saying 'Record to update not found,' which means that the bot tried to update something, but it did not exist at that time, so it threw an error. Did you delete the bot while adding a datasource ?

**Comment by n4ze3m** [comment] 2023-09-09 07:30
Are you using version v0.0.27, right? I will look into it.

**Comment by zhangmazi** [comment] 2023-09-09 07:32
> Are you using version v0.0.27, right? I will look into it.

i use the lastest of your github and the lastest master branch.

i run docker-compose with ./docker.

**Comment by n4ze3m** [comment] 2023-09-09 07:34
Which data source did you use? PDF?

**Comment by zhangmazi** [comment] 2023-09-09 07:48
source is :https://n4ze3m.com/projects
but i guess the reason, because i am in china, GWF(great wall firewall).
1.GWF, it can fetch openapi on GWF
2. WARP, openapi is banned WARP..

so bad... i hate GFW. fk

**Comment by n4ze3m** [comment] 2023-09-09 07:54
Sorry for that :/  dialoqbase support Llama v2 models via fireworks.ai ? Does it work there?

**Comment by zhangmazi** [comment] 2023-09-09 07:57
thanks. i will try.

**Comment by n4ze3m** [comment] 2023-09-09 08:03
Hey, just asking, how did you find the dialoqbase repo? The repo has received so many stars in the last few days from China 😊 Anyways, thanks for using it! ❤️

**Comment by zhangmazi** [comment] 2023-09-09 08:12
i have found by DouYin.com.

i have try deploy once agent just now in USA VPS. but it is not work too. so bad.

**Comment by n4ze3m** [comment] 2023-09-09 08:13
> i have try deploy once agent just now in USA VPS. but it is not work too. so bad.

Same issue ?

**Comment by zhangmazi** [comment] 2023-09-09 08:15
![image](https://github.com/n4ze3m/dialoqbase/assets/1011088/0dfa84ea-d28a-4161-b14c-ea01b8f8d0bc)
![image](https://github.com/n4ze3m/dialoqbase/assets/1011088/2d70849e-5a30-4f1b-be69-cc40f97477d9)

nothing... and pq BotDocument have nothing too.

**Comment by n4ze3m** [comment] 2023-09-09 08:18
Can you add a datasource once more and check it instead of the website?

**Comment by n4ze3m** [comment] 2023-09-09 08:19
I will try to reproduce what happened and release a patch :)

**Comment by zhangmazi** [comment] 2023-09-09 08:21
![image](https://github.com/n4ze3m/dialoqbase/assets/1011088/50279fee-bda4-48a2-bc42-d1921518b803)

![image](https://github.com/n4ze3m/dialoqbase/assets/1011088/24c2b5da-85a1-40f9-b6e1-e43904076daa)

openai chatgpt key is valid.

**Comment by n4ze3m** [comment] 2023-09-09 08:32
Oh, okay. Are you using a premium OpenAI API key, not the trial one? Because a few months ago, a similar issue happened when a person used a free trial API key, which now won't work.

you can test your openai key on [chatbotui](https://github.com/mckaywrigley/chatbot-ui) : https://github.com/mckaywrigley/chatbot-ui

**Comment by zhangmazi** [comment] 2023-09-09 08:35
> Can you add a datasource once more and check it instead of the website?

![image](https://github.com/n4ze3m/dialoqbase/assets/1011088/a4ded6e9-24e5-439f-8269-2d334ace311b)
![image](https://github.com/n4ze3m/dialoqbase/assets/1011088/f903ec53-ab6b-433c-82df-8d20bd9f7bbd)


the same issue. it can not work.

**Comment by zhangmazi** [comment] 2023-09-09 08:38
> 

![image](https://github.com/n4ze3m/dialoqbase/assets/1011088/7630fbf7-7251-48dc-a577-9f2eb2af1bbf)


my key is valid.

**Comment by n4ze3m** [comment] 2023-09-09 08:40
Oh, sorry, is dialoqbase docker's redis up too?

**Comment by zhangmazi** [comment] 2023-09-09 08:40
yes. redis pgvector dialoqbase is running and up ok.

> Oh, sorry, is dialoqbase docker's redis up too?哦，对不起，dialoqbase docker 的 redis 也启动了吗？

**Comment by n4ze3m** [comment] 2023-09-09 08:44
Okay, I will check what happened and post an update here

**Comment by n4ze3m** [comment] 2023-10-04 19:03
Hey, v1 has been released with improved queue support, which may resolve your issue. If you test it, please let me know. Thanks!

**Closed** 2023-11-08 17:46 UTC
Labels: bug
