### ISSUE TITLE
Ollama asking for API Key: "Unable to validate API key".

### ISSUE THREAD

**Issue by mjtechguy** [n4ze3m/dialoqbase#200] opened 2024-01-25 21:16 UTC
Hello,

I was able to successfully add an Ollama server and select a model to use. When I try to use that model, I get an error: 

"Unable to validate API key".

Ollama should not require an API key. Any ideas?

![image](https://github.com/n4ze3m/dialoqbase/assets/29070994/002c2b64-89c1-4552-a2b1-14b0d71b2bf3)

**Comment by n4ze3m** [comment] 2024-01-26 04:22
Hey, the error is because of the `ollama embedding`  you selected, which is deprecated. You can add Ollama embedding models the same way you added the Ollama chat model by going to 'Models' and selecting 'Embedding'

**Comment by HyperUpscale** [comment] 2024-01-26 12:51
> Hey, the error is because of the `ollama embedding` you selected, which is deprecated. You can add Ollama embedding models the same way you added the Ollama chat model by going to 'Models' and selecting 'Embedding'

I decoded your reply:
![image](https://github.com/n4ze3m/dialoqbase/assets/126105457/23c92b81-b388-4287-b080-76369c24ddc6)


And it seem to pass that problem.

But then we have a NEW message :) 
![image](https://github.com/n4ze3m/dialoqbase/assets/126105457/9c56b610-adc3-45f3-911f-47551b5be97e)

That means it doesn't update the config...

I tried manually, but I don't know how it will work:
![image](https://github.com/n4ze3m/dialoqbase/assets/126105457/4e4df33e-991d-4ff6-b0a6-4e775d8e2dae)

Gives the same NEW error.

PLEASE HELP!

BTW it doesn't work with localhost, 127.0.0.1... it finds the ollama server with host.docker.internal. Maybe that is related IDK

**Comment by n4ze3m** [comment] 2024-01-26 13:18
> Gives the same NEW error.

Hey, sorry about the error. What error is it throwing now?

**Comment by HyperUpscale** [comment] 2024-01-26 17:22
I don't understand ... there are always new error from somewhere @_@

![image](https://github.com/n4ze3m/dialoqbase/assets/126105457/8b689f4c-ac90-4ac6-af93-5b6364968629)


In the docker console:

> Error: Request to Ollama server failed: 404 Not Found
    at OllamaEmbeddings._request (/app/node_modules/@langchain/community/dist/embeddings/ollama.cjs:101:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (/app/node_modules/p-retry/index.js:50:12) {
  attemptNumber: 7,
  retriesLeft: 0
}<

It seems to me that the web interface is kinda independent from the config, or the docker.
Because now **the Web UI accept the model and embedding settings,** but the dont work on the backend (docker).
Example of what I am saying: on the Web page in the config the address ONLY  "http://host.docker.internal:11434" is accepted, but it that doesn't work when the docker image tries to get my ollama (I forgot to mention it is on WSL, not docker)

So all in all it seems like the local host IP network is conflicting the code. It does it with LiteLLM the same way Dialoqbase.

Somehow you (also LiteLLM) are reffering to the local host in specific  way, because of tens of other projects work with the current setup.
One of them is Ollama web UI - using docker and it finds and works with ollama on "http://host.docker.internal:11434"

Another tip: My host IPs are a complicated story... not sure if from the WSL of from the Docker... For that is what confuses the dialoqbase. 
![image](https://github.com/n4ze3m/dialoqbase/assets/126105457/048236ae-04df-4fdd-9473-09683f2d540c)

Now I am trying to figure out the docker network... ... ...

**Comment by n4ze3m** [comment] 2024-01-26 18:06
> In the docker console:

Interesting that you added the Ollama chat model via the editor, but are you still experiencing the issue, right?

If you successfully added the Ollama model, then there is no problem with the chat model. The issue is caused by the embedding model you configured. Can you double-check the model ID?

**Comment by HyperUpscale** [comment] 2024-01-26 18:50
![image](https://github.com/n4ze3m/dialoqbase/assets/126105457/60b40ce3-bc96-425f-94e5-0be3bb25b980)

IDK

![image](https://github.com/n4ze3m/dialoqbase/assets/126105457/f3698bf0-a842-492a-bbda-322a7f5a0533)

**Comment by n4ze3m** [comment] 2024-01-26 19:03
Hey, I think I found an issue not related to Docker (just tested it on my Windows WSL) too.

Can you try using zephyr:7b-beta as the chat model along with any other embedding model (use Xenova/all-Min-L6-v2) and send a message? It should work.

There will be a new release in 2 or 3 hours that fixes the above issues (hopefully).

**Comment by HyperUpscale** [comment] 2024-01-26 19:12
![image](https://github.com/n4ze3m/dialoqbase/assets/126105457/bc0282ec-5290-491a-8a5d-1c7d7c981dfc)

http://host.docker.internal:11434/ is the only way that HALF works for me... I don't know if that will be for everyone :D

**Comment by HyperUpscale** [comment] 2024-01-26 19:20
Wait.... 
IT WORKS ... WHEN I REMOVE THE STREAM OPTION FROM THE MODEL

**Comment by n4ze3m** [comment] 2024-01-26 19:26
That's a strange bug. I will look into it. Which version of Ollama are you using?

Also, do not remove `{question}` from the prompt.

**Comment by HyperUpscale** [comment] 2024-01-26 19:31
ollama version is 0.1.20

**Comment by n4ze3m** [comment] 2024-01-26 19:38
I tested Ollama mainly on Llama2 and Mistral; both of them work fine for me. I released a few Ollama-related fixes; you can pull the latest in 1 or 2 hours.

**Comment by n4ze3m** [comment] 2024-01-26 19:39
Try another model you have locally to see if it's working fine. :)

**Comment by n4ze3m** [comment] 2024-01-26 19:40
Hey @mjtechguy, I have released the bug fixes that will resolve your issues. :)

**Comment by mjtechguy** [comment] 2024-01-31 04:36
Would it be possible to call the ollama embedding endpoint? 

https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings 

This would allow for the offloading to a remote ollama node running on a GPU.

Thanks!

**Comment by n4ze3m** [comment] 2024-01-31 04:41
Yes, You can configure Ollama embedding in chat models by following these steps:

- Go to admin models.
- Select 'embedding.'
- Add the Ollama URL and choose the model from which you want to generate embedding. (The UI will be enhanced in the coming version.)

Please let me know if you encounter any issues.

**Comment by n4ze3m** [comment] 2024-03-05 17:57
Hey, I'm closing this issue. I have upgraded the way to add Ollama models on the latest version. Also, if you're looking for a simple Ollama web UI, you can try out https://pageassist.n4ze3m.com/, which doesn't require Docker or anything else, just a simple Chrome extension.

**Closed by n4ze3m** 2024-03-05 17:57 UTC
Labels: bug

**Comment by mjtechguy** [comment] 2024-03-05 18:45
This is awesome. Both the improvements to Dialoqbase but also the Pageassist Chrome extension. Thank you @n4ze3m you are a master at your craft.

**Comment by n4ze3m** [comment] 2024-03-05 18:56
Hey @mjtechguy , omggg thank you for sponsoring!!! Did you double-check the amount??? 🤯 You can cancel it if it's wrong. 🤗

**Comment by mjtechguy** [comment] 2024-03-05 19:00
I did it for $10 a month but it seems it billed me for a year. I am ok with that as I will definitely continue to use both Dialoqbase and PageAssist in my day to day work. Thank you again @n4ze3m

**Comment by n4ze3m** [comment] 2024-03-05 19:07
Hey, I'm really happy to hear about it! 🤗 More improvements are coming to Dialoqbase and Page Assist in the coming weeks. Also I'm totally happy you can cancel it 😄
