### ISSUE TITLE
Youtube Import

### ISSUE THREAD

**Issue by rossman22590** [n4ze3m/dialoqbase#93] opened 2023-09-30 21:03 UTC
Youtube never proceeds after processing, never succeeds. I am trying out /next branch

2023-09-30 21:00:21.691462770 [W:onnxruntime:, graph.cc:3490 CleanUnusedInitializersAndNodeArgs] Removing initializer '/model/decoder/layers.0/self_attn_layer_norm/Constant_output_0'. It is not used by any node and should be removed from the model.

2023-09-30 21:00:21.691479421 [W:onnxruntime:, graph.cc:3490 CleanUnusedInitializersAndNodeArgs] Removing initializer '/model/decoder/layers.1/self_attn_layer_norm/Constant_1_output_0'. It is not used by any node and should be removed from the model.

2023-09-30 21:00:21.691489628 [W:onnxruntime:, graph.cc:3490 CleanUnusedInitializersAndNodeArgs] Removing initializer '/model/decoder/layers.1/self_attn_layer_norm/Constant_output_0'. It is not used by any node and should be removed from the model.

2023-09-30 21:00:21.691496026 [W:onnxruntime:, graph.cc:3490 CleanUnusedInitializersAndNodeArgs] Removing initializer '/model/decoder/layers.2/encoder_attn_layer_norm/Constant_1_output_0'. It is not used by any node and should be removed from the model.

2023-09-30 21:00:21.691502890 [W:onnxruntime:, graph.cc:3490 CleanUnusedInitializersAndNodeArgs] Removing initializer '/model/decoder/layers.1/encoder_attn_layer_norm/Constant_output_0'. It is not used by any node and should be removed from the model.

2023-09-30 21:00:21.691517128 [W:onnxruntime:, graph.cc:3490 CleanUnusedInitializersAndNodeArgs] Removing initializer '/model/decoder/layers.1/encoder_attn_layer_norm/Constant_1_output_0'. It is not used by any node and should be removed from the model.

2023-09-30 21:00:21.691531626 [W:onnxruntime:, graph.cc:3490 CleanUnusedInitializersAndNodeArgs] Removing initializer '/model/decoder/layers.0/self_attn_layer_norm/Constant_1_output_0'. It is not used by any node and should be removed from the model.

2023-09-30 21:00:21.691537135 [W:onnxruntime:, graph.cc:3490 CleanUnusedInitializersAndNodeArgs] Removing initializer '/model/decoder/layers.2/encoder_attn_layer_norm/Constant_output_0'. It is not used by any node and should be removed from the model.

2023-09-30 21:00:21.691542335 [W:onnxruntime:, graph.cc:3490 CleanUnusedInitializersAndNodeArgs] Removing initializer '/model/decoder/layer_norm/Constant_output_0'. It is not used by any node and should be removed from the model.

2023-09-30 21:00:21.691546489 [W:onnxruntime:, graph.cc:3490 CleanUnusedInitializersAndNodeArgs] Removing initializer '/model/decoder/layers.3/final_layer_norm/Constant_output_0'. It is not used by any node and should be removed from the model.

[info] load ffmpeg-core

[info] loading ffmpeg-core

[info] ffmpeg-core loaded

ffmpeg loaded

[info] run FS.writeFile ./audio.mp3 <23527313 bytes binary file>

[info] run ffmpeg command: -i ./audio.mp3 -acodec pcm_s16le -ac 1 -ar 16000 ./audio.wav

[fferr] ffmpeg version v0.11.0-6-g16758e9d2b Copyright (c) 2000-2020 the FFmpeg developers

[fferr]   built with emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.34 (57b21b8fdcbe3ebb523178b79465254668eab408)

[fferr]   configuration: --target-os=none --arch=x86_32 --enable-cross-compile --disable-x86asm --disable-inline-asm --disable-stripping --disable-programs --disable-doc --disable-debug --disable-runtime-cpudetect --disable-autodetect --extra-cflags='-O3 --closure=1 -I/work/ffmpeg.wasm-core/build/include -s USE_PTHREADS=1' --extra-cxxflags='-O3 --closure=1 -I/work/ffmpeg.wasm-core/build/include -s USE_PTHREADS=1' --extra-ldflags='-O3 --closure=1 -I/work/ffmpeg.wasm-core/build/include -s USE_PTHREADS=1 -L/work/ffmpeg.wasm-core/build/lib' --pkg-config-flags=--static --nm=llvm-nm --ar=emar --ranlib=emranlib --cc=emcc --cxx=em++ --objcc=emcc --dep-cc=emcc --enable-gpl --enable-nonfree --enable-zlib --enable-libx264 --enable-libx265 --enable-libvpx --enable-libwavpack --enable-libmp3lame --enable-libfdk-aac --enable-libtheora --enable-libvorbis --enable-libfreetype --enable-libopus --enable-libwebp --enable-libass --enable-libfribidi

[fferr]   libavutil      56. 51.100 / 56. 51.100

[fferr]   libavcodec     58. 91.100 / 58. 91.100

[fferr]   libavformat    58. 45.100 / 58. 45.100

[fferr]   libavdevice    58. 10.100 / 58. 10.100

[fferr]   libavfilter     7. 85.100 /  7. 85.100

[fferr]   libswscale      5.  7.100 /  5.  7.100

[fferr]   libswresample   3.  7.100 /  3.  7.100

[fferr]   libpostproc    55.  7.100 / 55.  7.100

[fferr] Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './audio.mp3':

[fferr]   Metadata:

[fferr]     major_brand     : mp42

[fferr]     minor_version   : 0

[fferr]     compatible_brands: isommp42

[fferr]     creation_time   : 2023-09-30T16:56:01.000000Z

[fferr]   Duration: 00:02:55.33, start: 0.000000, bitrate: 1073 kb/s

[fferr]     Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 942 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)

[fferr]     Metadata:

[fferr]       creation_time   : 2023-09-30T16:56:01.000000Z

[fferr]       handler_name    : ISO Media file produced by Google Inc. Created on: 09/30/2023.

[fferr]     Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)

[fferr]     Metadata:

[fferr]       creation_time   : 2023-09-30T16:56:01.000000Z

[fferr]       handler_name    : ISO Media file produced by Google Inc. Created on: 09/30/2023.

[fferr] Stream mapping:

[fferr]   Stream #0:1 -> #0:0 (aac (native) -> pcm_s16le (native))

[fferr] Output #0, wav, to './audio.wav':

[fferr]   Metadata:

[fferr]     major_brand     : mp42

[fferr]     minor_version   : 0

[fferr]     compatible_brands: isommp42

[fferr]     ISFT            : Lavf58.45.100

[fferr]     Stream #0:0(und): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s (default)

[fferr]     Metadata:

[fferr]       creation_time   : 2023-09-30T16:56:01.000000Z

[fferr]       handler_name    : ISO Media file produced by Google Inc. Created on: 09/30/2023.

[fferr]       encoder         : Lavc58.91.100 pcm_s16le

[fferr] size=       1kB time=00:00:00.04 bitrate= 269.7kbits/s speed=0.0206x

[fferr] size=    2816kB time=00:01:36.43 bitrate= 239.2kbits/s speed=35.6x

[fferr] size=    5479kB time=00:02:55.33 bitrate= 256.0kbits/s speed=56.6x

[fferr] video:0kB audio:5479kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.001390%

[ffout] FFMPEG_END

[info] run FS.readFile ./audio.wav

[Program terminated with exit(0)] undefined

**Comment by rossman22590** [comment] 2023-09-30 21:07
get this in railway, using template - 2023-09-30 21:06:27.309696302 [W:onnxruntime:, graph.cc:3490 CleanUnusedInitializersAndNodeArgs] Removing initializer '/model/decoder/layers.1/encoder_attn_layer_norm/Constant_output_0'. It is not used by any node and should be removed from the model.
@replica: b15e8a61-e85d-465d-9176-46e7ade17582

**Comment by n4ze3m** [comment] 2023-10-01 03:56
Hey YouTube, MP3 and MP4 processing takes up a significant amount of CPU, and the current version of the application hangs when processing it. This issue will be resolved in the upcoming v1 update :)

**Comment by n4ze3m** [comment] 2023-10-03 13:40
> get this in railway, using template - 2023-09-30 21:06:27.309696302 [W:onnxruntime:, graph.cc:3490

There is some issue with TransformerJS and Railway.app. I will look into what happened and update here

**Comment by rossman22590** [comment] 2023-10-11 08:19
Working now?

**Comment by rossman22590** [comment] 2023-10-15 09:50
you rock!

**Comment by n4ze3m** [comment] 2023-11-18 05:57
Hey, the railway template has been updated. Also, keep in mind that processing YouTube, MP3, and MP4 files may take some time, possibly up to 5 minutes

**Comment by rossman22590** [comment] 2023-11-18 06:07
do i need to reinstall?

**Comment by n4ze3m** [comment] 2023-11-18 06:21
I believe the issue was caused by a Docker mount. Try reinstalling; since you are using Supabase, there should be no issues with the database.

**Comment by n4ze3m** [comment] 2023-11-20 07:49
I'm closing this. If you still have the issue, please reopen it. Thanks.

**Closed by n4ze3m** 2023-11-20 07:49 UTC
Labels: bug
